<?php

$inv_def = "Intended investment is the natural or legal person is in his or his using his experience or his or his money in undertaking economic projects, whether alone or in combination with natural or legal person domestic or foreign, with the state or its citizens to create a project or joint projects.";
$inv_def .="<br/>And knew also that employ investment money in order to achieve revenue or income or profit, but this definition misses target host countries to invest.";
$inv_def .="Investment can be defined in financial point of view and business point of view as: ";
$inv_def .="In finance, investment is the purchase of a financial product or other item of value with";
$inv_def .="an expectation of favorable future returns. In general terms, investment means the";
$inv_def .="use money in the hope of making more money. In business, investment is the purchase by";
$inv_def .="a producer of a physical good, such as durable equipment or inventory, in the hope of";
$inv_def .="improving future business. <br/>";



$risk = "A risk is a possibility or probability or rather a chance that in the future you may incur a ";
$risk .="loss with respect to your investment.";
$risk .="Also called market risk or non-diversifiable risk, systematic risk is the fluctuation of ";
$risk .="returns caused by the macroeconomic factors that affect all risky assets.  ";
$risk .="Unsystematic risk is the risk that something with go wrong on the company or industry";
$risk .="level, such as mismanagement, labor strikes, production of undesirable products, etc. ";
$risk .="Systematic risk + Unsystematic risk = Total risk";

$agri = "With a growing population of more than 80mn, Egypt represents one of the largest markets in the region.";
$agri .= "The government has made development of the agricultural sector a priority,";
$agri .= "ensuring continued levels of investment, the country's food production industry is ";
$agri .= "better developed than that in many neighboring states, creating strong export ";
$agri .= "opportunities.";
$agri .= "Egypt’s ";
$agri .= "sophisticated food processors are creating products and packaging that are high in ";
$agri .= "quality, competitively priced and attractive to global markets.";

$suez = "The Suez Canal is crucial to both global shipping and to the Egyptian economy, with the ";
$suez .= "Waterway representing one of the biggest revenue-generators in Egyptian trade.";
$suez .= " It connects the Red Sea to the Mediterranean and acts as the country's major source of foreign currency,";
$suez .= " which is also generated by oil and gas exports, tourism and remittances from Egyptians living abroad.";


$health="HealthCare is simply caring for people and their lives.";
$health.="Egypt has a long history in health care and medical practice, which dates back to Pharisaic times. In recent decades, the country has achieved several improvements both in health indicators and health care provision.";
$health="The Egyptian government has undertaken an ambitious reform of the national healthcare system, to build on a reputation as an excellent source of healthcare in the region and as a major destination for both health tourism and investment. As a result the government pledging to involve the private sector in every aspect of the economic reform process, the healthcare sector is well positioned for a healthy expansion.";

$edu = "Egypt’s education sector creates and serves the largest workforce in the Middle East and North Africa and is ripe with investment opportunities. Looking abroad, Egypt has seen how much the private sector can bring to educational development, from private education to public-private partnerships for K-12 schooling, from private university and technical/vocational education to corporate training programs. There are currently 2.5 million university students. Served by 39 universities (20 public and 19 private), total number of students enrolled in private institutes reached 313931 in June 2012. The government investments in university and higher education are estimated to reach about EGP 4.1 billion in 2012/2013.";
$edu .="<br/><br/>The number of public schools increased from 36 thousand schools in the year 2006/2007 to more than 40 thousand schools in the year 2010/2011 of which 5662 school are private ";
$edu .="Schools. Total the government will invest about EGP 4.5 billion for pre-university education in plan 2012/2013. The illiteracy rate dropped from 85.7% in 1927 to 25.1% in 2010.";

$edu .="<br/><br/>Egypt is open to foreign participation in both higher education and training for the demands of the global marketplace. Moreover, corporate education brands enjoy significant cachet, catering to a growing private-sector appetite for courses ranging from driver-education and security training to high-end professional courses and seminars.";
$edu .="Egypt’s premiere public-private partnership in education is the Egyptian Education ";
$edu .="Initiative (EEI) launched in concert with the World Economic Fund. The EEI supports education reform through the use of communication and information technology tools in partnership with some of the world’s leading IT firms, including HP, Cisco, Oracle, IBM and Siemens. Other collaborative efforts between the government and the private sector have lead to widespread access to technology by installing computer Labs in 2000 schools, while connecting 1120 schools to the internet, and create about 1954 community level IT club.";

$edu2 ="";
$edu2 .="Egypt has a long history as an education innovator and for decades has been an exporter of well-educated labor. Today, a growing percentage of young people prefer to stay in Egypt and work at both home-grown giants and multinationals. To do so, they need globally competitive skills — both soft skills and industry-specific training and education. As a result, in addition to the traditional elementary through university education system, vocational and corporate training programs are becoming increasingly popular. Corporate programs teach skills including time management, sales and marketing, human resources and finance, grooming promising employees for management positions. C-suite executives benefit from advanced professional seminars, while blue-collar and semi-skilled workers are taking vocational courses to upgrade their skills. Barely a decade old, has the corporate training sector abounded in potential. ";
$edu2 .="<br/>As Egypt grows, so will demand for schools providing cutting-edge, global-quality education and training — demand fuelled by both parents and students, who have always recognized the importance of education in building their own futures and that of Egypt.";

$tour = "<br/> Egypt’s tourism industry is among the most diverse and vibrant in the world. Beyond the ";
$tour .= "pristine beaches and year-round sunshine, Egypt’s long and varied history, rich cultural ";
$tour .= "heritage and unique geographic features make it a popular destination for adventure, eco, ";
$tour .= "sailing, diving, health and cultural tourism — and for religious tourism to sites of ";
$tour .= "importance to Christians and Muslims alike.";
$tour .= "<br/><br/>";
$tour .= "Although well-served by five-star properties, there is considerable room for investment in ";
$tour .= "the three- and four-star hospitality segments. Other highly promising sectors include niche experiences as residential tourism, health and medical tourism, therapeutic tours, providing nature and desert safaris, eco-tourism , and adventures travel.";


$it = "Egypt’s communications and information technology sector is a leading global outsourcing destination ranked fourth on A.T. Kearney’s 2011 Global Services Location Index (GSLI). This puts Egypt ahead of competitors in the region including UAE with ranked 15th.. Egypt, one of the highest-growth potential IT markets in the Middle East, is receiving increasing attention from tier-one vendors and distributors, most of which are already very familiar with the market. Given the huge population, rising economy and relatively low PC penetration, the country will continue to be an important market over the forecast period. ";
$it .="<br/><br/>A pro-active policy and clear long-term vision by the government of Egypt, in partnership with the private sector, seeks to make the CIT sector a key one in the country’s economy.";
$it .="<br/><br/>Egypt offers easy access to markets in the Arabian Gulf, the Levant, North Africa and Sub Saharan Africa as well as Europe. Open to the world and investor-friendly, Egypt is an ideal location to base a business with regional – and even global - ambitions. It is a key communications node, notably hosting SEA-ME-WE2, the world’s first submarine cable linking South-East Asia, the Middle East and Europe.";
$it .="<br/>Leading global players ranging Intel and Oracle to Orange and Vodafone have established product development divisions and call centers serving global operations. Home-grown players are making their marks nationally, regionally and globally. ";
$it .="Egypt’s CIT businesses cover the entire sector. Call centers based in Egypt serve customers worldwide at all ends of the value chain. Software developers produce Arabic-language solutions for major global software packages and plug-ins for popular English-language programs from Adobe and Microsoft, to name but two. A research-based technology house created part of the global Wi-MAX standard. ";


$energy="With the expected depletion of natural gas reserves within the next 57 years,";
$energy.=" Egypt is an investor’s dream when it comes to sustainable energy resources. ";


$energy.= "Egypt possesses an abundance of land, sunny weather and high wind speeds, making it a";
$energy.=" prime resource for three renewable energy sources: wind, solar and biomass. ";


$energy.="<br/><br/>Recent political changes have not affected Egypt’s long term commitment ";
$energy.="to renewable energies. The promotion of renewable energies became a political aim that is shared";
$energy.=" across the political spectrum. Although renewable energy is";
$energy.=" relatively a new market in Egypt, the country’s strategic location and the government’s";
 $energy.="commitment to increasing its renewable energy output make it an attractive investment opportunity.";


 $energy.="A new policy framework had been approved in February 2008 that fosters an investor friendly system ";
$energy.="and encourages foreign as well as private sector involvement. The government expects the renewable";
$energy.=" energy sector to produce 20% of total power generation by 2020, 12% of which will be generated by";

$energy.=" wind energy. Priority sectors are wind farms (the most cost-effective renewable energy source), ";
$energy.="followed by biodiesel production, both of which are supported by the country’s abundance of land,";


 $energy .="stable climate conditions and competitive labor force.";


$energy .=" With solar energy costs expected to decline";

$energy.="sharply over the next 5 to 7 years, ";

$energy.="Egypt aims to develop a competitive market in solar energy, but sees more immediate opportunities in";
$energy.=" wind and biomass.";
$energy.="<br/><br/>Given the need to reduce dependence on gas, it is hoped that Egypt will place greater";

$energy.=" emphasis on its considerable solar and wind potential. During the period 2011-2016, Egypt's overall power";
 $energy.="generation is expected to increase by an annual average of 4.5%, reaching 178.8 terawatt hours. ";
$energy.="This includes annual increases in excess of 9% for renewable-based electricity supply. Egypt has set";
$energy.=" a target of producing 12% of its power from wind and a total of 20% from renewable by 2020. It is ";
$energy.="also looking to attract US$110bn of investment into its power sector by 2027. Egypt plans to boost ";
$energy.="dramatically the portion of energy coming from renewable sources, getting 20% of the projected 60 ";
$energy.="giga-watts (GW) of demand in 2020 from renewable. Wind would provide around 7.2GW of that total.";



$risk2 ="The question you might have at this point is, 'Why would I want to risk losing some or all of my money?' In fact, you might not want to put money at risk that you expect to need in the short term—to make the down payment on a home, for example, or pay a tuition bill for next semester, or cover emergency expenses. By taking certain risks with the rest of your money, however, you may earn dividends or interest. In addition, the value of the assets you purchase may increase over the long term.";
$risk2 .="<br/><br/>If you prefer to avoid risk and put your money in an FDIC-insured certificate of deposit (CD) at your bank, the most you can earn is the interest that the bank is paying. This may be good enough in some years, say, when interest rates are high or when other investments are falling. But on average, and over the long haul, stocks and bonds tend to grow more rapidly, which would make it easier or even possible to reach your savings goals. That's because avoiding investment risk entirely provides no protection against inflation, which decreases the value of your savings over time.";
$risk2 .="<br/><br/>On the other hand, if you concentrate on only the riskiest investments, it's entirely possible, even likely, that you will lose money.";
$risk2 .="<br/><br/>For many people, it's best to manage risk by building a diversified portfolio that holds several different types of investments. This approach provides the reasonable expectation that at least some of the investments will increase in value over a period of time. So even if the return on other investments is disappointing, your overall results may be positive.";



?>